# vi roles/web/tasks/gunicorn.yml
#########################
---
- name: copying gunicorn service and socket files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - { src: 'gunicorn.service.j2', dest: '/etc/systemd/system/gunicorn.service' }
    - { src: 'gunicorn.socket.j2', dest: '/etc/systemd/system/gunicorn.socket' }
  notify: sudo systemctl daemon-reload

- name: copying gunicorn config file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ django_user }}"
    group: "{{ django_user }}"
    mode: '0644'
  loop:
    - { src: 'gunicorn.conf.py.j2', dest: '{{ project_etc_path }}/gunicorn.conf.py' }
  become_user: "{{ django_user }}"
  notify: sudo systemctl restart gunicorn

- name: sudo systemctl enable --now gunicorn
  service:
    name: gunicorn
    state: started
    enabled: yes
#########################
