# vi roles/database/handlers/main.yml
#########################
---
- name: sudo systemctl restart postgresql
  service:
    name: "postgresql-{{ postgresql_version }}"
    state: restarted
#########################
